package dao;

import model.Order;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_0
     *
     * @mbggenerated Thu Dec 13 16:56:26 CST 2018
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_0
     *
     * @mbggenerated Thu Dec 13 16:56:26 CST 2018
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_0
     *
     * @mbggenerated Thu Dec 13 16:56:26 CST 2018
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_0
     *
     * @mbggenerated Thu Dec 13 16:56:26 CST 2018
     */
    Order selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_0
     *
     * @mbggenerated Thu Dec 13 16:56:26 CST 2018
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_0
     *
     * @mbggenerated Thu Dec 13 16:56:26 CST 2018
     */
    int updateByPrimaryKey(Order record);
}