package dao;

import model.OrderItem;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbggenerated Wed Dec 12 20:56:34 CST 2018
     */
    int deleteByPrimaryKey(Long orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbggenerated Wed Dec 12 20:56:34 CST 2018
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbggenerated Wed Dec 12 20:56:34 CST 2018
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbggenerated Wed Dec 12 20:56:34 CST 2018
     */
    OrderItem selectByPrimaryKey(Long orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbggenerated Wed Dec 12 20:56:34 CST 2018
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbggenerated Wed Dec 12 20:56:34 CST 2018
     */
    int updateByPrimaryKey(OrderItem record);
}