package model;

public class Order {

    @Override
    public String toString() {
        return "Order{" +
                "orderId=" + orderId +
                ", userId=" + userId +
                ", status='" + status + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_0.order_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_0.user_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_0.status
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_0.order_id
     *
     * @return the value of t_order_0.order_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_0.order_id
     *
     * @param orderId the value for t_order_0.order_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_0.user_id
     *
     * @return the value of t_order_0.user_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_0.user_id
     *
     * @param userId the value for t_order_0.user_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_0.status
     *
     * @return the value of t_order_0.status
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_0.status
     *
     * @param status the value for t_order_0.status
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}