package model;

public class OrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item_0.order_item_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    private Long orderItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item_0.order_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item_0.user_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item_0.order_item_id
     *
     * @return the value of t_order_item_0.order_item_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    public Long getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item_0.order_item_id
     *
     * @param orderItemId the value for t_order_item_0.order_item_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item_0.order_id
     *
     * @return the value of t_order_item_0.order_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item_0.order_id
     *
     * @param orderId the value for t_order_item_0.order_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item_0.user_id
     *
     * @return the value of t_order_item_0.user_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item_0.user_id
     *
     * @param userId the value for t_order_item_0.user_id
     *
     * @mbggenerated Thu Dec 13 12:17:12 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}